name: Scheduled Playwright Tests
on:
  schedule:
    - cron: '0 * * * *' # Every hour at minute 0 UTC
  workflow_dispatch: # Optional: allows manual triggering
jobs:
  data-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run data-setup tests
        run: npx playwright test --project=data-setup
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Upload petData.json
        uses: actions/upload-artifact@v4
        with:
          name: pet-data
          path: tests/petData.json
  get-pet-online-store:
    needs: data-setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Download petData.json
        uses: actions/download-artifact@v4
        with:
          name: pet-data
          path: tests/
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run get-pet tests
        run: npx playwright test --project=get-pet-online-store
        env:
          API_KEY: ${{ secrets.API_KEY }}
  update-pet-online-store:
    needs: data-setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Download petData.json
        uses: actions/download-artifact@v4
        with:
          name: pet-data
          path: tests/
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run update-pet tests
        run: npx playwright test --project=update-pet-online-store
        env:
          API_KEY: ${{ secrets.API_KEY }}
  create-pet-online-store:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run create-pet tests
        run: npx playwright test --project=create-pet-online-store
        env:
          API_KEY: ${{ secrets.API_KEY }}
